-- PostgreSQL 17.x EXPLAIN 扩展（SERIALIZE/MEMORY）占位

CREATE TEMP TABLE t AS SELECT generate_series(1, 100000) AS id, md5(random()::text) AS s;
CREATE INDEX ON t (id);

-- 示例：EXPLAIN (ANALYZE, BUFFERS, WAL, SUMMARY, MEMORY)
EXPLAIN (ANALYZE, BUFFERS, WAL, SUMMARY) SELECT * FROM t WHERE id BETWEEN 100 AND 200;


