name: Knowledgebase Quality Check

on:
  push:
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown

      - name: Run quality checker
        run: |
          python Analysis/quality_checker.py Analysis/ --format json --output Analysis/quality_report_latest.json

      - name: Upload quality report
        uses: actions/upload-artifact@v4
        with:
          name: quality-report-latest
          path: Analysis/quality_report_latest.json 